version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exam-proctoring-app
    ports:
      - "3001:3001"   # Only expose backend (serves frontend too)
    volumes:
      - videos-data:/app/videos
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  videos-data:
    driver: local
